apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: n7i8ootb2-nodejs 
  janus-idp.io/tekton: n7i8ootb2-nodejs
  backstage.io/kubernetes-id: n7i8ootb2-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: n7i8ootb2-nodejs
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml